<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2018/10/26
 * Time: 5:14 PM
 */

namespace App\HttpController\Home;


use App\HttpController\Base;
use App\Logic\WEBConfig;
use EasySwoole\EasySwoole\ServerManager;
use EasySwoole\EasySwoole\Trigger;
use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Http\Message\Status;
use EasySwoole\Spl\SplBean;
use EasySwoole\Validate\Validate;

abstract class HomeBase extends Base
{
    protected $WEBConfig;

    function onRequest(?string $action): ?bool
    {
        parent::onRequest($action); // TODO: Change the autogenerated stub
        $this->WEBConfig = WEBConfig::getInstance()->getConfig();
        $logic = new \App\Logic\Home\Article();
        $categoryList = $logic->getCategoryListByHome(null, 1, 30);
        $tagList = $logic->getTagList(null, 1, 30);
        $topList = $logic->getTopArticleList(null, 1, 20);
        $newCommentList = $logic->getNewCommentList(null, 1, 10);
        $linkList = $logic->getLinkListByHome(null, 1, 30);

        $this->assign([
            'categoryList'   => $categoryList,
            'tagList'        => $tagList,
            'topList'        => $topList,
            'newCommentList' => $newCommentList,
            'linkList'       => $linkList,
            'navActive'      => 'index',
            'web_statistics' => $this->WEBConfig['WEB_STATISTICS'],
            'ADMIN_EMAIL'    => $this->WEBConfig['ADMIN_EMAIL'],
            'WEB_ICP_NUMBER' => $this->WEBConfig['WEB_ICP_NUMBER'],
            'title'          => $this->WEBConfig['WEB_NAME'],
            'keywords'       => $this->WEBConfig['WEB_KEYWORDS'],
            'description'    => $this->WEBConfig['WEB_DESCRIPTION'],
            'author'         => $this->WEBConfig['AUTHOR'],
        ]);
        return true;
    }

}